site_name: 'rtl-rag-chatbot-api'
site_description: 'RTL RAG CHATBOT API'

nav:
  - Introduction: index.md

plugins:
  - techdocs-core

markdown_extensions:
  - tables
  - plantuml_markdown:
      server: https://www.plantuml.com/plantuml
