[tool.poetry]
name = "rag_pdf_api"
version = "1.0.0"
description = "rag-pdf-api"
authors = []
readme = 'README.md'

[[tool.poetry.source]]
name = "python-packages"
url = "https://gitlab.com/api/v4/projects/42761560/packages/pypi/simple/"
secondary = true


[tool.poetry.dependencies]
python = ">=3.8.1,<4.0"
fastapi = "^0.109.0"
uvicorn = "^0.27.1"
starlette-exporter = "^0.21.0"

[tool.poetry.dev-dependencies]
pytest = "^7.1.0"
pytest-cov = "^3.0.0"
pytest-sugar = "^0.9.4"
httpx = "^0.26.0"
isort = "^5.10.1"
black = "^23.3.0"
flake8 = "^6.0.0"
pre-commit = "^2.15.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]

[tool.poetry.scripts]
start = "rag_pdf_api.app:start"
