global:
  env: dev
  vault:
    mount_path: "da/itowe/ci"
    secrets_prefix: "common"
    envSecrets:
      - chatbot/chatbot-api

universal-helm-chart:
  ingress:
    domains:
      - rtl-rag-chatbot-api.itowe.gcp.dev.da-service.io
  deployment:
    scaleDown: true

gcp:
  project_id: "dat-itowe-dev"
