global:
  env: dev
  vault:
    mount_path: "da/itowe/ci"
    secrets_prefix: "common"
    envSecrets:
      - chatbot/chatbot-api
universal-helm-chart:
  ingress:
    iap: false
    domains:
      - rtl-rag-chatbot-api.itowe.gcp.dev.da-service.io
    annotations:
      prometheus.io/probe: "true"
      prometheus.io/probe-scheme: https
      prometheus.io/probe-module: http_3xx_ssl_verify_iap_header
      kyverno.io/require-iap-monitoring-annotations: "ignore"
  deployment:
    scaleDown: true
gcp:
  project_id: "dat-itowe-dev"
