global:
  env: preprod
universal-helm-chart:
  ingress:
    iap: false
    domains:
      - rtl-rag-chatbot-api.itowe.gcp.preprod.da-service.io
    annotations:
      prometheus.io/probe: "true"
      prometheus.io/probe-scheme: https
      prometheus.io/probe-module: http_3xx_ssl_verify_iap_header
      kyverno.io/require-iap-monitoring-annotations: "ignore"
  deployment:
    scaleDown: false #Placeholder for user input from developer portal
    replicaCount: 4
  container:
    resources:
      requests:
        cpu: 500m
        memory: 1Gi
      limits:
        cpu: 700m
        memory: 2Gi
  gcpProject: "dat-itowe-pre"
gcp:
  project_id: "dat-itowe-pre"
