global:
  env: preprod
universal-helm-chart:
  ingress:
    domains:
      - rtl-rag-chatbot-api.itowe.gcp.preprod.da-service.io
  deployment:
    scaleDown: false #Placeholder for user input from developer portal

gcp:
  project_id: "dat-itowe-pre"
