global:
  env: prod
universal-helm-chart:
  ingress:
    iap: false
    domains:
      - rtl-rag-chatbot-api.itowe.gcp.prod.da-service.io
    annotations:
      prometheus.io/probe: "true"
      prometheus.io/probe-scheme: https
      prometheus.io/probe-module: http_3xx_ssl_verify_iap_header
      kyverno.io/require-iap-monitoring-annotations: "ignore"
  deployment:
    scaleDown: false
    replicaCount: 2
gcp:
  project_id: "dat-itowe-prd"
