global:
  env: prod
universal-helm-chart:
  ingress:
    iap: false
    domains:
      - rtl-rag-chatbot-api.itowe.gcp.prod.da-service.io
    annotations:
      prometheus.io/probe: "true"
      prometheus.io/probe-scheme: https
      prometheus.io/probe-module: http_3xx_ssl_verify_iap_header
      kyverno.io/require-iap-monitoring-annotations: "ignore"
  deployment:
    scaleDown: false
    replicaCount: 4
  container:
    resources:
      requests:
        cpu: 800m
        memory: 2Gi
      limits:
        cpu: 1000m
        memory: 4Gi
gcp:
  project_id: "dat-itowe-prd"
gcpProject: "dat-itowe-prd"
