apiVersion: v2
type: application
name: rtl-rag-chatbot-api
version: "4.0.10"
dependencies:
  - name: universal-helm-chart
    repository: oci://europe-west1-docker.pkg.dev/mgr-platform-prod-khsu/charts
    version: 2.4.1-2.4.1
