apiVersion: v2
type: application
name: rtl-rag-chatbot-api
version: "3.0.0"
dependencies:
  - name: universal-helm-chart
    repository: oci://europe-west1-docker.pkg.dev/mgr-platform-prod-khsu/charts
    version: 3.1.3-3.5.3
