apiVersion: v2
type: application
name: rtl-rag-chatbot-api
version: "3.2.0"
dependencies:
  - name: universal-helm-chart
    repository: oci://europe-west1-docker.pkg.dev/mgr-platform-prod-khsu/charts
    version: 2.1.3-2.1.3
