kind: ServiceAccount
apiVersion: v1
metadata:
  name: chatbot-api
  namespace: "{{ .Release.Namespace }}"
  labels:
    app: chatbot-api
  annotations:
    iam.gke.io/gcp-service-account: chatbot-api@{{ .Values.gcpProject }}.iam.gserviceaccount.com
